<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/10/22 15:35:12
sfConfig::add(array(
  'mod_betyolo_category_enabled' => true,
  'mod_betyolo_category_view_class' => 'sfPHP',
));
